---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
resources:
- ArgocdApp.yaml
- Project0.yaml
- Project1.yaml
- Project2.yaml
