apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: smcp
  namespace: smcp
spec:
  security:
    controlPlane:
      mtls: false
    dataPlane:
      mtls: true
      automtls: true
    manageNetworkPolicy: false
  tracing:
    type: Jaeger
    sampling: 10000
  gateways:
    openshiftRoute:
      enabled: true  
    ingress:
      runtime:
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 3
            minReplicas: 1
            targetCPUUtilizationPercentage: 80
          replicas: 1
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  version: v2.2