# Default values for zerotrust_app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaces:
  prefix: project
  count: "3"
  annotations: {}

deployments:
  prefix: app-
  count: "4"
  replicaCount: 2
  podAnnotations: 
    sidecar.istio.io/inject: "true"
  podSecurityContext: {}
  securityContext: {}

  image:
    repository: quay.io/jotak/hey-ho
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

service:
  type: ClusterIP
  port: 8080
