# Default values for zerotrust_app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaces:
  prefix: project
  count: "3"
  annotations: {}

deployments:
  prefix: app-
  count: "4"
  replicaCount: 2
  podAnnotations: 
    sidecar.istio.io/inject: "false"
  podSecurityContext: {}
  securityContext: {}

  image:
    repository: quay.io/jotak/hey-hotrue
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  resources: 
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

service:
  type: ClusterIP
  port: 8080
